#!/usr/bin/env python
#
# Copyright 2001-2005 Free Software Foundation
#
# This file is part of GNU Enterprise.
#
# GNU Enterprise is free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License as published by the Free Software Foundation; either
# version 2, or (at your option) any later version.
#
# GNU Enterprise is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public
# License along with program; see the file COPYING. If not,
# write to the Free Software Foundation, Inc., 59 Temple Place
# - Suite 330, Boston, MA 02111-1307, USA.
# 
# $Id: gnue-schema,v 1.1 2007/10/04 18:20:15 oleg Exp $

import os
import sys

if hasattr (sys, 'frozen'):
  sys.path.append (os.path.abspath (os.path.dirname (sys.argv[0])))

from gnue.common.datasources.readgsd import gsdClient

if __name__ == "__main__":
  gsdClient ().run ()
